apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-backend
  labels:
    app: fullstack-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack-backend
  template:
    metadata:
      labels:
        app: fullstack-backend
    spec:
      containers:
      - name: fullstack-backend
        image: sidjunior/fullstack-backend:7fbcc03722fb3b4038c4bc947ca6264c72650da0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-backend-service
spec:
  selector:
    app: fullstack-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP