apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack-backend
  template:
    metadata:
      labels:
        app: fullstack-backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15
          command: ['sh', '-c', 'until pg_isready -h postgres-service -p 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: fullstack-backend
          image: sidjunior/fullstack-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres123@postgres-service:5432/tarefas_db"
