apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-frontend
  labels:
    app: fullstack-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack-frontend
  template:
    metadata:
      labels:
        app: fullstack-frontend
    spec:
      containers:
      - name: fullstack-frontend
        image: sidjunior/fullstack-frontend:7fbcc03722fb3b4038c4bc947ca6264c72650da0
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-frontend-service
spec:
  selector:
    app: fullstack-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP