apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- postgres-simple.yaml


images:
- name: fullstack-backend
  newName: sidjunior/fullstack-backend
  newTag: 57bf02e7784866fe24aa89770d824dae465658d5
- name: fullstack-frontend
  newName: sidjunior/fullstack-frontend
  newTag: 57bf02e7784866fe24aa89770d824dae465658d5
