apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- postgres-simple.yaml


images:
- name: fullstack-backend
  newName: sidjunior/fullstack-backend
  newTag: c058c7c780e9483c0dee628022df5278acf7050e
- name: fullstack-frontend
  newName: sidjunior/fullstack-frontend
  newTag: c058c7c780e9483c0dee628022df5278acf7050e
