apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- postgres-simple.yaml


images:
- name: fullstack-backend
  newName: sidjunior/fullstack-backend
  newTag: c65153da8d85622119468f70ed37e7c80f9e36da
- name: fullstack-frontend
  newName: sidjunior/fullstack-frontend
  newTag: c65153da8d85622119468f70ed37e7c80f9e36da
